version: '3'
services:
  mongodb:
    image: mongo:4.4
    ports:
      - "27017:27017"
  mongo-express:
    image: mongo-express:0.54.0
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
